version: '3'

services:

  speech:
    build: speech
    command: cd speech && python speech.py
    networks: 
      - backend
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: postgres
    networks:
      - backend
  


# Networks to be created to facilitate communication between containers

networks:
  backend: